spring:
  application:
    name: jan-2024-java-spring-my-hw

  #  Налаштувати підключення до бази даних (для докера)
  datasource:
    url: "jdbc:postgresql://localhost:5432/XXX"
    username: "postgres"
    password: "postgres"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # none для міграції